### PR TITLE
feat: add Dockerfile

### PR DESCRIPTION
**Pull request by ungarscool1**
## Description

In order to improve the deployment process at home, I have created a Dockerfile to create a replicable image anywhere.

Still need to implement the CI to build the container image automatically.

This pull request includes changes to the `.dockerignore` file and the `Dockerfile` to enhance the Docker setup for the project. The most important changes include adding new entries to the `.dockerignore` file and creating a multi-stage build process in the `Dockerfile`.

Changes to `.dockerignore`:

* Added `*.md` and `auxiliary` to ignore markdown files and the auxiliary directory.

Changes to `Dockerfile`:

* Created a multi-stage build process using `alpine:latest` for downloading and unzipping assets, followed by `nginx:latest` to serve the files.
* Added commands to install necessary packages, download and unzip a map file, and clean up the build directory.
* Configured the NGINX server to serve the unzipped map files and set the default HTML file to `index.html`.

### CODE REVIEW

**Comment by Dreamfarer** [comment]
LGTM, thank you very much! 🚀

I just realized I’ve never uploaded the API code, and I’m committed to rectifying that. Currently, the API is implemented as a PHP script with a MySQL server running in the background. Each index in a single table stores a single height value. Since this solution seems outdated to me, I’m considering refactoring it.

For this endeavor, I’d greatly appreciate your input—if you’re willing to share:

1. **Which language should I use to rewrite the small API script?** Should I use Java, Node.js, or something else?  
2. **Is a database the most efficient choice for this use case?** Considering that the data stored consists of only a single height value per index, would you still recommend using a database, or might a file-based solution be better?  
3. **Should I create a separate container for the API, or include it in the same container?** If I create a separate container, would you recommend creating a new repository for this, or restructuring the existing one?  

I’m planning to start working on this at the end of next week. If I don’t hear back from you by then, I’ll make a decision based on my limited knowledge.

**Review by Dreamfarer — APPROVED** [review]
LGTM, thank you very much! 🚀

**Comment by ungarscool1** [comment]
Hi,

> Which language should I use to rewrite the small API script?

It depends on what you want to do, it's a good project to learn a new programming language. I would use Golang for this, because it's a single binary, fast, and strongly supports concurrency. However, you can keep consistency, as you use a lot of JS in this project, you may prefer to use NodeJS.

> Is a database the most efficient choice for this use case?

To me, it's the most efficient choice, as you request by `x, y`. The problem with the file-based system is when you have several requests at the same time it will struggle because, on a large dataset, the FS will be slower. If you don't want to run a MySQL server, you can look at SQLite.

> Should I create a separate container for the API, or include it in the same container?

[It should/must be in another container than the front end, each container is a unique service](https://docs.docker.com/engine/containers/multi-service_container/#:~:text=It%27s%20best%20practice%20to%20separate%20areas%20of%20concern%20by%20using%20one%20service%20per%20container).


I hope that will help you, I am not a good explainer 😬

**Comment by Dreamfarer** [comment]
Very useful and greatly appreciated. Thank you @ungarscool1! ❤️

**Pull request merged**
